"""Update Appointment Model

Revision ID: b2a77c9ad81c
Revises: 5fab77825ae9
Create Date: 2026-03-15 01:21:56.292325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a77c9ad81c'
down_revision: Union[str, Sequence[str], None] = '5fab77825ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_emergency', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'is_emergency')
    # ### end Alembic commands ###
